//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDbAction")]
    public interface IDbAction {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/SaleBeetween2013_2014", ReplyAction="http://tempuri.org/IDbAction/SaleBeetween2013_2014Response")]
        object SaleBeetween2013_2014();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/SaleBeetween2013_2014", ReplyAction="http://tempuri.org/IDbAction/SaleBeetween2013_2014Response")]
        System.Threading.Tasks.Task<object> SaleBeetween2013_2014Async();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/SumSaleInDay", ReplyAction="http://tempuri.org/IDbAction/SumSaleInDayResponse")]
        object SumSaleInDay(int d, int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/SumSaleInDay", ReplyAction="http://tempuri.org/IDbAction/SumSaleInDayResponse")]
        System.Threading.Tasks.Task<object> SumSaleInDayAsync(int d, int m, int y);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/NumberOfSoldProduct", ReplyAction="http://tempuri.org/IDbAction/NumberOfSoldProductResponse")]
        object NumberOfSoldProduct(string name, string lastname);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IDbAction/NumberOfSoldProduct", ReplyAction="http://tempuri.org/IDbAction/NumberOfSoldProductResponse")]
        System.Threading.Tasks.Task<object> NumberOfSoldProductAsync(string name, string lastname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDbActionChannel : WcfServiceClient.ServiceReference1.IDbAction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DbActionClient : System.ServiceModel.ClientBase<WcfServiceClient.ServiceReference1.IDbAction>, WcfServiceClient.ServiceReference1.IDbAction {
        
        public DbActionClient() {
        }
        
        public DbActionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DbActionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbActionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DbActionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object SaleBeetween2013_2014() {
            return base.Channel.SaleBeetween2013_2014();
        }
        
        public System.Threading.Tasks.Task<object> SaleBeetween2013_2014Async() {
            return base.Channel.SaleBeetween2013_2014Async();
        }
        
        public object SumSaleInDay(int d, int m, int y) {
            return base.Channel.SumSaleInDay(d, m, y);
        }
        
        public System.Threading.Tasks.Task<object> SumSaleInDayAsync(int d, int m, int y) {
            return base.Channel.SumSaleInDayAsync(d, m, y);
        }
        
        public object NumberOfSoldProduct(string name, string lastname) {
            return base.Channel.NumberOfSoldProduct(name, lastname);
        }
        
        public System.Threading.Tasks.Task<object> NumberOfSoldProductAsync(string name, string lastname) {
            return base.Channel.NumberOfSoldProductAsync(name, lastname);
        }
    }
}
